### ISSUE TITLE
Please add support for extensible 0.3

### ISSUE THREAD

**Issue by peti** [fumieval/elevator#2]
http://packdeps.haskellers.com/feed?needle=elevator

**Comment by fumieval** [comment]
Modified on hackage.

**Comment by peti** [comment]
And that modified builds succeeds for you? I seem to get errors: http://hydra.cryp.to/build/574422/log/raw

**Comment by fumieval** [comment]
Sorry, actually I need to correct the source. I uploaded the corrected version.
